// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvYxzdLtjQnmHZdK1iYkwwpr4PcBN97IU',
    appId: '1:345975094249:web:4ce68819c21bd954b6e978',
    messagingSenderId: '345975094249',
    projectId: 'curdfirebase-26cab',
    authDomain: 'curdfirebase-26cab.firebaseapp.com',
    storageBucket: 'curdfirebase-26cab.appspot.com',
    measurementId: 'G-1Q99ZQH5FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQHuuxn8pOMPRSNd29LjePTJXPF8-2PWI',
    appId: '1:345975094249:android:468e01d9944ba5c8b6e978',
    messagingSenderId: '345975094249',
    projectId: 'curdfirebase-26cab',
    storageBucket: 'curdfirebase-26cab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCMqwLkTg8RM5aVUHXZfHNwZRwU_tgHq4',
    appId: '1:345975094249:ios:0b57d54314104de5b6e978',
    messagingSenderId: '345975094249',
    projectId: 'curdfirebase-26cab',
    storageBucket: 'curdfirebase-26cab.appspot.com',
    iosBundleId: 'com.example.aiBlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCMqwLkTg8RM5aVUHXZfHNwZRwU_tgHq4',
    appId: '1:345975094249:ios:2b56b0fbee573972b6e978',
    messagingSenderId: '345975094249',
    projectId: 'curdfirebase-26cab',
    storageBucket: 'curdfirebase-26cab.appspot.com',
    iosBundleId: 'com.example.aiBlog.RunnerTests',
  );
}
