class AppSecrets {
  static const String supabaseUrl='https://zoeqjfvwydcvrnakvxlz.supabase.co';
  static const String supabaseAnnonKey='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZXFqZnZ3eWRjdnJuYWt2eGx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjMxODE0NDIsImV4cCI6MjAzODc1NzQ0Mn0.f6lGvGoeRsXILr81ahcNq1Mfie1KoJuci0ZYQne5tLc';
}